# create_banners.yml
-----
- name: Add a message to /etc/motd
  hosts: all
  become: yes
  tasks:
       -name: Display banner on Linux Server
    lineinfile:
        path: /etc/motd     
        line:
        "*************************************************
                  Prodcution Server
        *************************************************"
        create: yes
        
