# create_banners.yml
-----
- name: Apply banners on different types of Linux servers
  hosts: inventory.yml
  become: yes
  tasks:

       -name: Set web server banner
    lineinfile:
      path: /etc/motd
      state: present
      create: yes
      line:
        *************************************************
                 Prodcution Server
        *************************************************
