- name: Display PMON and Tns processes upon root login
  hosts: inventory.yml
  become: true
  tasks:
    -name: Ensure PMON and TNS commands are added to root's bash profile
    lineinfile:
      path: ~/.bash_profile
      state: present
      create: yes
      line:
      ps -ef | grep pmon
      ps -ef | grep tns
      
